name: my_first_workflow

on:
  push:
    branches:
      - main 
jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: greeting
        run: echo "Everyone Shall sit under their own vine and fig tree ..."

   job_two:
     run-on: ubuntu-latest
     steps:
       - uses: actions/checkout@4
       - name: goodbye
         run: echo "Jesus Christ"
